name: CI

on:
  push:
  # uncomment before opening PR
  #   branches: [master]
  # pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9"]

    env:
      # this was in the original Travis CI definition
      MPLBACKEND: Agg

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v6

      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: strict
          activate-environment: isochrones-test
          auto-update-conda: false

      - name: Install isochrones
        run: |
          conda install -q -y -c conda-forge \
            numpy numba cython pytables pandas \
            multinest pymultinest \
            pytest pytest-cov
          pip install .

      # first see if tests run at all before we try caching
      - name: Cache data
        id: cache-data
        uses: actions/cache@v6
        with:
          path: ~/.isochrones
          key: mist-grid-v1-${{ runner.os }}
          restore-keys: |
            isochrones-test-data-v1-

      # this would use old Travis CI script to download data if it isn't cached
      # but it seems to be broken
      # - name: Download data
      #   if: steps.cache-mist.outputs.cache-hit != 'true'
      #   run: mist-initialize.py

      # Travis CI script just ran after the tests
      # but this just uses the pytest coverage plugin
      - name: Run tests
        run: pytest -v --cov --cov-report=term-missing
